### ISSUE TITLE
error leads to permanently frozen time 

### ISSUE THREAD

**Issue by kotoroshinoto** [jorgamun/PauseInMultiplayer#1]
[Pause in Multiplayer] This mod failed in the GameLoop.UpdateTicking event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at PauseInMultiplayer.PauseInMultiplayer.GameLoop_UpdateTicking(Object sender, UpdateTickingEventArgs e) in C:\Users\William\source\repos\PauseInMultiplayer\PauseInMultiplayer\PauseInMultiplayer.cs:line 541
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 126
   
i'm not sure what caused this in order to reproduce, but both players connected to my hosted instance were temporarily disconnected (their clients indicated the server cut the connection) around the time the time freeze started

advancing a day moved the time to 6 AM, but didn't restore the clock, time and npcs remained frozen.

**Comment by brucethemoose** [comment]
I've gotten this same issue before as well. Had to restart the day to fix it. 

Might be related to my other issue, as the nullref error message looks the same: https://github.com/jorgamun/PauseInMultiplayer/issues/2

**Comment by jorgamun** [comment]
Well, that's no good. Next time this happens, if you could, try to get me all the SMAPI logs from every player you can with as much context as you can.

**Comment by brucethemoose** [comment]
For what it's worth, I only got this error to trigger once in the first in-game year (and unfortunately didn't save that log), but I haven't managed to reproduce it since then either. And we trigger pauses most in-game days.
